---
# tasks file for jenkins
- name: "Add jenkins key"
  apt_key:
    state: present
    url: "{{ jenkins_key_ubuntu }}"

- name: "Add Jenkins Binary repository"
  apt_repository:
    filename: "Jenkins"
    repo: "deb https://pkg.jenkins.io/debian binary/"

- name: "Install Java and Jenkins"
  apt:
    name: "{{ item.value.name }}"
    state: present
  loop: "{{ lookup('dict',software) }}"

- name: "Starting jenkins"
  service:
    name: "jenkins"
    state: started
    enabled: yes

- name: "Save default password"
  command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  register: result

- name: "Install Git Plugin"
  jenkins_plugin:
    name: "git"

- name: "Showing init password jenkins"
  debug:
    var: result.stdout