---
# tasks file for jenkins
- name: "Add jenkins key"
  apt_key:
    state: present
    url: "{{ jenkins_key_ubuntu }}"

- name: "Add Jenkins Binary repository"
  apt_repository:
    filename: "Jenkins"
    repo: "deb https://pkg.jenkins.io/debian binary/"

- name: "Install Java and Jenkins"
  apt:
    name: "{{ item.value.name }}"
    state: present
  loop: "{{ lookup('dict',software) }}"

- name: "Starting jenkins"
  service:
    name: "jenkins"
    state: started
    enabled: yes

- name: "Save default password"
  command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  register: result

- name: "Showing init password jenkins"
  debug:
    var: result.stdout

# - name: Get the jenkins-cli jarfile from the Jenkins server
#   get_url:
#     url: "http://{{ jenkins_hostname }}:8080/jnlpJars/jenkins-cli.jar"
#     dest: "{{ jenkins_jar_location }}"
#   register: jarfile_get
#   until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
#   retries: 5
#   delay: 10

#- name: "Install PLugins"
#  include: plugins.yml